CREATE TABLE TEAM_LEADER 
( 
	TL_CODE         INT    NOT NULL,
	TL_NAME         VARCHAR(20)    NOT NULL,
    HIRE_YMD         DATE    NOT NULL,
	PRIMARY KEY (TL_CODE)
    
); 

INSERT INTO 	TEAM_LEADER  (TL_CODE, TL_NAME, HIRE_YMD)
     VALUES 	(101, 'KanuKim97', '2023-03-18');
     
INSERT INTO 	TEAM_LEADER  (TL_CODE, TL_NAME, HIRE_YMD)
     VALUES 	(102, 'Luna828 ', '2023-03-18');